#
# docker-compose -f ./docker/docker-compose.yml build
# docker-compose -f ./docker/docker-compose.yml up -d
#

version: '2'
services:
  node-websocket-vs-socket.io:
    image: "derand/node-websocket-vs-socket.io"
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: node-websocket-vs-socket.io
    hostname: node-websocket-vs-socket.io
    ports:
      - "3001:3001"
      - "3002:3002"
